#ifndef _LOG_H_
#define _LOG_H_

#define DATASE_CORRECT_NOTIFICATION "DATABASE SET UP"
#define CLIENT_ACCEPTED "A NEW CLIENT WAS ACCEPTED"
#define CLIENT_DISCONNECTED "A CLIENT WAS DISCONNECTED"
#define TWEET_NOTIFICATION "%s POSTED A TWEET WITH ID: %s -> %s"
#define LIKE_NOTIFICATION "TWEET WITH ID %d WAS LIKED"
#define REFRESH_NOTIFICATION "REFRESH REQUESTED"
#define SHOW_NOTIFICATION "TWEET WITH ID %d WAS REQUESTED"

#define MAX_NOTIFICATION 200

#endif
