#ifndef _LOG_H_
#define _LOG_H_

#define DATASE_CORRECT_NOTIFICATION "DATABASE SET UP CORRECTLY"
#define CLIENT_ACCEPTED "A NEW CLIENT WAS ACCEPTED"
#define CLIENT_DISCONNECTED "A CLIENT WAS DISCONNECTED"
#define TWEET_NOTIFICATION "'%s' POSTED A TWEET -> %s"
#define LIKE_NOTIFICATION "TWEET WITH ID %d WAS LIKED"
#define REFRESH_NOTIFICATION "REFRESH REQUESTED"
#define SHOW_NOTIFICATION "TWEET WITH ID %d WAS REQUESTED"
#define DELETE_NOTIFICATION "TWEET WITH ID %d WAS DELETED BY USER '%s'"
#define LOGOUT_NOTIFICATION "USER '%s' LOGGED OUT"
#define LOGIN_NOTIFICATION "USER LOGGED IN AS '%s' "
#define CANNOT_LOGIN_NOTIFICATION "WARNING: CANNOT LOGIN USER. ALREADY LOGGED AS '%s'"
#define CANNOT_INIT_SESSION "ERROR: CANNOT INITIATE SESSION"
#define CANNOT_OPEN_SESSION "ERROR: CANNOT OPEN SESSION"
#define CANNOT_CREATE_ADDRESS "ERROR: CANNOT CREATE ADRRESS"
#define CANNOT_CONNECT_DB "ERROR: CANNOT CONNECT TO DATABASE"
#define CANNOT_SEND_RESPONSE "WARNING: RESPONSE WAS NOT SENT"
#define ERROR_DB_RESPONSE "WARNING: ERROR ON DATABASE RESPONSE"
#define CLIENT_NOT_ACCEPTED "ERROR: CLIENT NOT ACCEPTED"
#define SERVER_READY "SERVER IS READY TO ACCEPT A CLIENT"
#define ACHIEVED_CONNECT_DATABSE "THREAD ACHIEVED CONNECTION TO DATABASE"

#define MAX_NOTIFICATION 1024

#define MSG_STOP    "exit"

#define CHECK(x) \
    do { \
        if (!(x)) { \
            fprintf(stderr, "%s:%d: ", __func__, __LINE__); \
            perror(#x); \
            exit(-1); \
        } \
    } while (0) \

#define INFO 1
#define WARNING 2
#define ERROR 3



#endif
